GET localhost:8080/sample?value=value

###

POST localhost:8080/sample
Content-Type: application/json

{
  "name": "",
  "email": "aaaaa"
}

###

POST localhost:8080/members
Content-Type: application/json

{
  "email": "aaaa@test.com"
}
